[package]
name = "gst-plugin-inter"
version = "0.11.0-alpha.1"
authors = ["Mathieu Duponchelle <mathieu@centricular.com>"]
license = "MPL-2.0"
description = "GStreamer Inter Plugin"
repository = "https://github.com/spiegela/gst-plugin-rs"
edition = "2021"
rust-version = "1.66"

[dependencies]
anyhow = "1"
gst = { package = "gstreamer", git="https://github.com/sdroege/gstreamer-rs", features = ["v1_18"] }
gst_utils = { package = "gstreamer-utils", git="https://github.com/sdroege/gstreamer-rs" }
gst_app = { package = "gstreamer-app", git="https://github.com/sdroege/gstreamer-rs" }
once_cell = "1.0"

[dev-dependencies]
pretty_assertions = "1"
gst-check = { package = "gstreamer-check", git="https://github.com/sdroege/gstreamer-rs" }
futures = "0.3"
tokio = { version = "1", features = ["fs", "macros", "rt-multi-thread", "time"] }
tokio-stream = "0.1.11"
serial_test = "2"

[lib]
name = "gstrsinter"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[build-dependencies]
gst-plugin-version-helper = { path="../../version-helper" }

[features]
static = []
capi = []
doc = ["gst/v1_18"]

[package.metadata.capi]
min_version = "0.8.0"

[package.metadata.capi.header]
enabled = false

[package.metadata.capi.library]
install_subdir = "gstreamer-1.0"
versioning = false

[package.metadata.capi.pkg_config]
requires_private = "gstreamer-1.0, gobject-2.0, glib-2.0, gmodule-2.0"

[[example]]
name = "plug-and-play"
